const libraryData = [
  { type: `spruch`, text: `📎 Hinweis gefunden: Das Glück war die ganze Zeit in dir. Fall geschlossen!`, file: `audio/tts/spruch-001.mp3` },
  { type: `spruch`, text: `🔮 Die Kristallkugel zeigt: Heute wird ein richtig guter Tag. Moment — er IST es schon!`, file: `audio/tts/spruch-002.mp3` },
  { type: `spruch`, text: `🕶️ Gute Detektive wissen: Die ungewöhnlichsten Spuren führen zu den besten Lösungen.`, file: `audio/tts/spruch-003.mp3` },
  { type: `spruch`, text: `🐝 Du bist wie eine Biene auf doppeltem Espresso — summst und schaffst alles!`, file: `audio/tts/spruch-004.mp3` },
  { type: `spruch`, text: `🌮 Sei dankbar für die Person, die Tacos erfunden hat. Und für dich. Beides echte Geschenke.`, file: `audio/tts/spruch-005.mp3` },
  { type: `spruch`, text: `🧗 Jeder Kletterer hat Momente, in denen er nach unten schaut. Und dann klettert er weiter.`, file: `audio/tts/spruch-006.mp3` },
  { type: `spruch`, text: `📋 Akte geschlossen: Du hast mehr drauf als du denkst. Bestätigt.`, file: `audio/tts/spruch-007.mp3` },
  { type: `spruch`, text: `🏰 Jedes Schloss wurde Stein für Stein gebaut — deine Ideen sind die ersten Steine.`, file: `audio/tts/spruch-008.mp3` },
  { type: `spruch`, text: `⛵ Auch im tiefsten Tal bist du auf dem Weg — einen Schritt nach dem anderen.`, file: `audio/tts/spruch-009.mp3` },
  { type: `spruch`, text: `✨ Dein Licht ist nicht erloschen — es sammelt gerade neue Kraft.`, file: `audio/tts/spruch-010.mp3` },
  { type: `spruch`, text: `🐢 Selbst Schildkröten stecken manchmal den Kopf raus. Du schaffst das auch!`, file: `audio/tts/spruch-011.mp3` },
  { type: `spruch`, text: `🐧 Du watschelst vor Freude wie ein Pinguin nach dem Frühstück. Süß!`, file: `audio/tts/spruch-012.mp3` },
  { type: `spruch`, text: `⚡ Die Magie in dir ist stärker als jeder Sturm — lass sie raus!`, file: `audio/tts/spruch-013.mp3` },
  { type: `spruch`, text: `💪 Agenten-Geheimnis: Wahre Stärke zeigt sich, wenn es schwer wird.`, file: `audio/tts/spruch-014.mp3` },
  { type: `spruch`, text: `📎 Geheimtipp: Drei tiefe Atemzüge. Ein... aus... ein... aus... ein... aus. Besser?`, file: `audio/tts/spruch-015.mp3` },
  { type: `spruch`, text: `🛸 Kein Asteroidengürtel kann dich aufhalten — du fliegst einfach durch!`, file: `audio/tts/spruch-016.mp3` },
  { type: `spruch`, text: `🔦 Taschenlampe aus. Notizbuch zu. Der Fall kann warten — du nicht.`, file: `audio/tts/spruch-017.mp3` },
  { type: `spruch`, text: `🗝️ Rätsel: Ich habe Städte, aber keine Häuser. Berge, aber keine Bäume. Was bin ich? (Eine Landkarte!)`, file: `audio/tts/spruch-018.mp3` },
  { type: `spruch`, text: `🗺️ Die wertvollste Entdeckung liegt nicht am Ende der Karte, sondern in deinem Herzen.`, file: `audio/tts/spruch-019.mp3` },
  { type: `spruch`, text: `🕵️ Jeder große Detektiv hatte Fälle, die ihm Angst gemacht haben — gelöst hat er sie trotzdem.`, file: `audio/tts/spruch-020.mp3` },
  { type: `spruch`, text: `�� Im Zirkus deiner Gedanken bist du der Star in der Manege — Vorhang auf!`, file: `audio/tts/spruch-021.mp3` },
  { type: `spruch`, text: `🌺 Leg dich gedanklich auf eine Wiese voller Wildblumen. Die Sonne wärmt dein Gesicht.`, file: `audio/tts/spruch-022.mp3` },
  { type: `spruch`, text: `🐸 Ein Frosch hat mal eine Prinzessin geküsst. Das war entweder sehr mutig oder sehr dumm. Beides okay.`, file: `audio/tts/spruch-023.mp3` },
  { type: `spruch`, text: `🍕 Inspiration ist wie Pizza: Es gibt keine schlechte. Manche ist nur besser als andere.`, file: `audio/tts/spruch-024.mp3` },
  { type: `spruch`, text: `🔍 Jede große Entdeckung beginnt mit einer einzigen Frage — stell sie!`, file: `audio/tts/spruch-025.mp3` },
  { type: `spruch`, text: `📋 Geheimauftrag: Finde drei Dinge in deiner Nähe, die die gleiche Farbe haben. Los!`, file: `audio/tts/spruch-026.mp3` },
  { type: `spruch`, text: `🌌 Im ganzen Universum gibt es nur eine Person wie dich — und das ist ziemlich cool.`, file: `audio/tts/spruch-027.mp3` },
  { type: `spruch`, text: `🧩 Das letzte Puzzleteil für heute: Ruhe. Morgen geht es weiter.`, file: `audio/tts/spruch-028.mp3` },
  { type: `spruch`, text: `🚀 Astronauten haben auch Angst vor dem Start — aber sie fliegen trotzdem.`, file: `audio/tts/spruch-029.mp3` },
  { type: `spruch`, text: `🛸 Außerirdische beneiden uns um drei Dinge: Sonnenuntergänge, Schokolade und Freundschaft.`, file: `audio/tts/spruch-030.mp3` },
  { type: `spruch`, text: `🏔️ Vom Gipfel aus sieht man: Der Weg war es wert. Jeder einzelne Schritt.`, file: `audio/tts/spruch-031.mp3` },
  { type: `spruch`, text: `🦄 Einhörner galoppieren vor Freude, wenn sie dich sehen — true story!`, file: `audio/tts/spruch-032.mp3` },
  { type: `spruch`, text: `🔍 Mut ist wie eine Lupe: Er hilft dir, klarer zu sehen, auch wenn es schwierig ist.`, file: `audio/tts/spruch-033.mp3` },
  { type: `spruch`, text: `💫 Die Sterne machen heute Nachtschicht — du darfst schlafen.`, file: `audio/tts/spruch-034.mp3` },
  { type: `spruch`, text: `🧭 Der Kompass deiner Neugier zeigt immer in die richtige Richtung.`, file: `audio/tts/spruch-035.mp3` },
  { type: `spruch`, text: `🤪 Verrückte Ideen sind wie Pizza: Am Anfang denkt man "Hmm", am Ende denkt man "GENIAL!"`, file: `audio/tts/spruch-036.mp3` },
  { type: `spruch`, text: `🤖 Roboter-Analyse: Dein Glücks-Algorithmus läuft perfekt. Keine Bugs, nur Freude.`, file: `audio/tts/spruch-037.mp3` },
  { type: `spruch`, text: `🧩 Wenn du alle guten Momente zusammenpuzzelst, ergibt sich ein wunderschönes Bild.`, file: `audio/tts/spruch-038.mp3` },
  { type: `spruch`, text: `🧙 Weiser Zaubererspruch: Wer das Kleine schätzt, dem wird das Große geschenkt.`, file: `audio/tts/spruch-039.mp3` },
  { type: `spruch`, text: `🏕️ Am Lagerfeuer zählen keine Likes — nur die Geschichten und die Freundschaft.`, file: `audio/tts/spruch-040.mp3` },
  { type: `spruch`, text: `🏔️ Der Berg sieht von unten riesig aus — aber du bist größer als jede Angst.`, file: `audio/tts/spruch-041.mp3` },
  { type: `spruch`, text: `🎭 Das Leben ist eine Bühne und deine Ideen sind der Hauptact.`, file: `audio/tts/spruch-042.mp3` },
  { type: `spruch`, text: `🎉 Plot-Twist: Das Beste an deinem Leben bist du selbst. Überraschung!`, file: `audio/tts/spruch-043.mp3` },
  { type: `spruch`, text: `🛰️ Mut ist kein Programm, das man installiert — es ist eine Entscheidung, die du triffst.`, file: `audio/tts/spruch-044.mp3` },
  { type: `spruch`, text: `⚡ Herunterfahren ist kein Fehler — es ist ein geplanter Neustart.`, file: `audio/tts/spruch-045.mp3` },
  { type: `spruch`, text: `🛸 Aliens sind auf die Erde gekommen — weil sie dein Lachen hören wollten.`, file: `audio/tts/spruch-046.mp3` },
  { type: `spruch`, text: `✨ Deine Willenskraft ist purer Sternenstaub — damit kann man Berge versetzen.`, file: `audio/tts/spruch-047.mp3` },
  { type: `spruch`, text: `🕵️ Ermittlungsergebnis: Deine gute Laune ist ansteckender als jeder Virus.`, file: `audio/tts/spruch-048.mp3` },
  { type: `spruch`, text: `🗺️ Deine Landkarte hat noch weiße Flecken — perfekt für neue Entdeckungen!`, file: `audio/tts/spruch-049.mp3` },
  { type: `spruch`, text: `😴 Dein Gehirn hat einen "Nicht stören"-Modus. Bitte jetzt aktivieren.`, file: `audio/tts/spruch-050.mp3` },
  { type: `spruch`, text: `🔎 Fun Fact: Sherlock Holmes hat nie "Elementar, mein lieber Watson" gesagt. Echt nicht!`, file: `audio/tts/spruch-051.mp3` },
  { type: `spruch`, text: `🌈 Dein Lächeln ist der stärkste Zauber im ganzen Königreich.`, file: `audio/tts/spruch-052.mp3` },
  { type: `spruch`, text: `🐧 Wusstest du, dass Pinguine ihrem Partner einen Stein schenken als Liebesbeweis? Romantisch, oder?`, file: `audio/tts/spruch-053.mp3` },
  { type: `spruch`, text: `🎪 Mut-Zirkus: Eintritt frei, Angst hat Platzverbot, und du bist der Hauptact!`, file: `audio/tts/spruch-054.mp3` },
  { type: `spruch`, text: `🌊 Das Meer erinnert dich: Es gibt unendlich viel Schönheit in der Welt.`, file: `audio/tts/spruch-055.mp3` },
  { type: `spruch`, text: `🌅 Jeder Sturm hat ein Ende — und danach kommt der schönste Sonnenaufgang.`, file: `audio/tts/spruch-056.mp3` },
  { type: `spruch`, text: `🧙 Der größte Zaubertrick? Gute Laune anstecken. Und den beherrschst du perfekt.`, file: `audio/tts/spruch-057.mp3` },
  { type: `spruch`, text: `��‍🚀 Nachricht aus dem All: "Wir können dein Lächeln von hier oben sehen!"`, file: `audio/tts/spruch-058.mp3` },
  { type: `spruch`, text: `🏔️ Du stehst auf dem Gipfel der guten Laune — und die Aussicht ist fantastisch!`, file: `audio/tts/spruch-059.mp3` },
  { type: `spruch`, text: `🌊 Fun Fact: Der Mariannengraben ist so tief, dass der Mount Everest darin verschwinden würde.`, file: `audio/tts/spruch-060.mp3` },
  { type: `spruch`, text: `🌅 Am Horizont wartet etwas, das genau zu dir passt — geh los und find es!`, file: `audio/tts/spruch-061.mp3` },
  { type: `spruch`, text: `🛸 In einer fernen Galaxie gibt es einen Planeten, auf dem alle nur chillen. Flieg hin. Gedanklich.`, file: `audio/tts/spruch-062.mp3` },
  { type: `spruch`, text: `🎶 Dein Tag hat einen Soundtrack: "Happy" auf Repeat!`, file: `audio/tts/spruch-063.mp3` },
  { type: `spruch`, text: `⛵ Es gibt eine Insel im Pazifik, die niemandem gehört. Was würdest du dort bauen?`, file: `audio/tts/spruch-064.mp3` },
  { type: `spruch`, text: `👩‍🚀 Mission "Mut": Schwierig, aber nicht unmöglich. Und du bist die beste Pilotin dafür.`, file: `audio/tts/spruch-065.mp3` },
  { type: `spruch`, text: `🌍 Auf diesem blauen Planeten hast du einen einzigartigen Platz — und der ist wertvoll.`, file: `audio/tts/spruch-066.mp3` },
  { type: `spruch`, text: `🔍 Fall "Unaufhaltsam" — Hauptverdächtige: Du! Beweislage: Überwältigend.`, file: `audio/tts/spruch-067.mp3` },
  { type: `spruch`, text: `🌿 Selbst der tiefste Dschungel wird hell, wenn du lachst.`, file: `audio/tts/spruch-068.mp3` },
  { type: `spruch`, text: `🕵️ Agenten-Anweisung: Ruhezustand aktivieren. Auch Spione brauchen Schlaf.`, file: `audio/tts/spruch-069.mp3` },
  { type: `spruch`, text: `🗂️ Tipp aus der Ermittlung: Schreib drei Dinge auf, die heute schön waren — es wirkt Wunder.`, file: `audio/tts/spruch-070.mp3` },
  { type: `spruch`, text: `🌅 Der Sonnenuntergang malt den Himmel in warmen Farben. Lehn dich zurück und schau zu.`, file: `audio/tts/spruch-071.mp3` },
  { type: `spruch`, text: `🌺 Pflücke einen gedanklichen Blumenstrauß aus all dem Guten in deinem Leben.`, file: `audio/tts/spruch-072.mp3` },
  { type: `spruch`, text: `🗝️ Du hast den Schlüssel zum Glück gefunden — Herzlichen Glückwunsch, Detektiv!`, file: `audio/tts/spruch-073.mp3` },
  { type: `spruch`, text: `⚙️ Deine innere Maschine läuft heute auf Höchstleistung. Genieß es!`, file: `audio/tts/spruch-074.mp3` },
  { type: `spruch`, text: `🔍 Fall "Pause machen": Sofort erledigen. Anordnung von ganz oben. Keine Diskussion.`, file: `audio/tts/spruch-075.mp3` },
  { type: `spruch`, text: `🧚 Feen-Challenge: Denk an fünf magische Dinge, die du gerne könntest. Fliegen zählt!`, file: `audio/tts/spruch-076.mp3` },
  { type: `spruch`, text: `🏕️ Das Lagerfeuer knistert leise. Die Sterne funkeln. Alles ist gut.`, file: `audio/tts/spruch-077.mp3` },
  { type: `spruch`, text: `💫 Jeder Stern am Himmel steht für einen schönen Moment in deinem Leben.`, file: `audio/tts/spruch-078.mp3` },
  { type: `spruch`, text: `😄 Danke-Liste: 1. Wochenende. 2. Pizza. 3. Dass du DU bist. Alles gleich wichtig.`, file: `audio/tts/spruch-079.mp3` },
  { type: `spruch`, text: `🌊 Wellen können einschüchtern — aber du bist die stärkste Schwimmerin.`, file: `audio/tts/spruch-080.mp3` },
  { type: `geschichte`, title: `Miras Weg durch den Nebelwald`, genre: `🧙 Fantasy`, preview: `🧙 Miras Weg durch den Nebelwald In dem kleinen Dorf am Fuß der Berge erzählte man sich Geschichten über den Nebelwald. Niemand ging freiwillig hinein....`, file: `audio/tts/story-01-nebelwald.mp3` },
  { type: `geschichte`, title: `Das Mädchen und der Glasdrache`, genre: `🧙 Fantasy`, preview: `🐉 Das Mädchen und der Glasdrache In der Stadt der tausend Türme lebte ein Mädchen namens Yara. Yara war gut in der Schule, nett zu allen, und lächelte...`, file: `audio/tts/story-02-glasdrache.mp3` },
  { type: `geschichte`, title: `Die Talent-Show-Katastrophe`, genre: `😂 Lustig`, preview: `🎭 Die Talent-Show-Katastrophe Es begann als die schlechteste Idee, die Lilly je hatte: Sie meldete sich für die Talent-Show an. Problem eins: Sie konn...`, file: `audio/tts/story-03-talentshow.mp3` },
  { type: `geschichte`, title: `ARI-7 und die Angst`, genre: `🚀 SciFi`, preview: `🤖 ARI-7 und die Angst ARI-7 war der fortschrittlichste Roboter auf der Raumstation Horizont. Sie konnte rechnen, steuern, reparieren, und 47 Sprachen ...`, file: `audio/tts/story-04-ari7.mp3` },
  { type: `geschichte`, title: `Drei Tage allein`, genre: `⛰️ Abenteuer`, preview: `🏕️ Drei Tage allein Das Survival-Camp hatte eine Abschlussprüfung: Drei Tage allein im Wald. Nur ein Messer, ein Feuerstein und eine Wasserflasche. Ja...`, file: `audio/tts/story-05-dreitage.mp3` },
  { type: `geschichte`, title: `Die Sternsammlerin`, genre: `🧙 Fantasy`, preview: `🌙 Die Sternsammlerin Naya hatte Angst vor der Dunkelheit. Jede Nacht lag sie wach, die Decke bis über die Nase gezogen, und starrte an die Decke. Eine...`, file: `audio/tts/story-06-sternsammlerin.mp3` },
  { type: `geschichte`, title: `Der Vortrag`, genre: `😂 Lustig`, preview: `😅 Der Vortrag Bens Vortrag war in fünf Minuten. Thema: "Mein Lieblingstier." Er hatte sich den Esel ausgesucht. (Gute Wahl.) Problem: Ben hatte PANIK ...`, file: `audio/tts/story-07-vortrag.mp3` },
  { type: `geschichte`, title: `Das verschwundene Lächeln`, genre: `🔍 Krimi`, preview: `🔍 Fall 17: Das verschwundene Lächeln In Emmas Klasse passierte etwas Seltsames: Alle hörten auf zu lächeln. Einer nach dem anderen. Erst Tim, dann Lar...`, file: `audio/tts/story-08-laecheln.mp3` },
  { type: `geschichte`, title: `Die Ritterin ohne Schwert`, genre: `🧙 Fantasy`, preview: `🏰 Die Ritterin ohne Schwert Im Königreich Sonnental gab es einen Ritterwettbewerb. Wer den Drachen auf dem Berg besiegt, wird zum Ritter geschlagen. A...`, file: `audio/tts/story-09-ritterin.mp3` },
  { type: `geschichte`, title: `Das Emotions-Update`, genre: `🚀 SciFi`, preview: `🌍 Das Emotions-Update Im Jahr 2085 erfand Dr. Chen ein Gefühls-Pflaster. Klebst du es auf, verschwinden alle negativen Gefühle. Keine Angst. Keine Tra...`, file: `audio/tts/story-10-emotionsupdate.mp3` },
];